[package]
name = "struart"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial2 = { version = "0.2.1", default-features = false }
thiserror = { version = "1.0.40", default-features = false }
